version: '3.8'
services:
  movies:
    image: viswanathkasi/movies:latest
    ports:
      - "8081:8080"
    deploy:
      replicas: 3
  train:
    image: viswanathkasi/train:latest
    ports:
      - "8082:8080"
    deploy:
      replicas: 3
  dth:
    image: viswanathkasi/dth:latest
    ports:
      - "8083:8080"
    deploy:
      replicas: 3
  recharge:
    image: viswanathkasi/recharge:latest
    ports:
      - "8084:8080"
    deploy:
      replicas: 3
